version: "3.8"

services:
  test:
    build:
      context: .
      target: builder
    hostname: test
    restart: always
    command: sh -c "go test -v ./..."
    depends_on: 
      db:
        condition: service_healthy
    environment:
      - ENV=dev
      - POSTGRES_HOST=rinha
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgpass
      - POSTGRES_DB=rinha
      - DATABASE_URL=postgres://postgres:pgpass@rinha:5432/rinha?sslmode=disable
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  api1:
    build: .
    hostname: api1
    restart: always
    expose:
      - "80"
    ports:
      - "80:80"
      - "9999:80"
      - "80:9999"
    network_mode: "host"
    depends_on: 
      db:
        condition: service_healthy
    environment:
      - ENV=dev
      - POSTGRES_HOST=rinha
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgpass
      - POSTGRES_DB=rinha
      - DATABASE_URL=postgres://postgres:pgpass@localhost:5432/rinha?sslmode=disable
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: rinha
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres", "-h", "rinha"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'
  
  migrate:
    image: migrate/migrate
    depends_on: 
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    command: -path=/migrations/ -database postgres://postgres:pgpass@db/rinha?sslmode=disable up
  
  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
